# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Regnipelk Blog
email: bodiddlie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming, Gamedev, Gaming, and other nerdy nonsense.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

author:
    twitter: bodiddlie
    github:  bodiddlie

# Build settings
markdown: kramdown

permalink: /:title/
